### ISSUE TITLE
Accept a validation schema as a GET param

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#126]
Pass it on to libhxl as a parsed JSON object (?)

**Comment by danmihaila** [comment]
@davidmegginson we think this is going to help us if we want to use some customizations from user.

**Comment by danmihaila** [comment]
@davidmegginson I think should be high priority. We need the option to send via POST and GET the content of the validation schema

**Comment by davidmegginson** [comment]
OK, moved back to the 4.7 (30 April) release.

**Comment by davidmegginson** [comment]
Realised that this issue belongs to the HXL Proxy, not libhxl. Closing here, and replacing with

HXLStandard/hxl-proxy#212
