### ISSUE TITLE
Include raw row number in error reports

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#134]
If it is available (depending on the type of data source), include the raw row number in error reports.

- [x] add unit tests
- [x] (re)implement in hxl.model.Dataset and hxl.io input classes
- [x] support in validation output (see #132 )
- [x] merge to test
- [x] update JSON validation spec to add _source\_row_
- [x] deploy to beta
- [x] update wiki

Originally reported by @alexandru-m-g in HXLStandard/hxl-proxy#202

**Comment by davidmegginson** [comment]
Deployed, and all docs updated.

**Comment by danmihaila** [comment]
tested!
