### ISSUE TITLE
Infer date and number formats and flag discrepancies

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#156]
The date and number validators ensure that cells contain dates and numbers respectively. They should be extended to look for the most common format and if that is above a threshold eg. 90%, then assume that all cells in that column should be using that format and flag any that aren't.

eg. if 99% contain dd/mm/yyyy and then one contains dd-mm-yyyy, then flag it

**Comment by davidmegginson** [comment]
During the planning meeting, there were some concerns that this could be confusing for users, especially with an arbitrary cutoff like 90%. We may delay this from the current milestone until we work out the user experience better.
