### ISSUE TITLE
Detect and support tab-separated as well as comma-separated data

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#159]
hxl.io.CSVInput should autodetect tab-separated vs comma-separated.

- [x] add unit test
- [x] implement detection
- [x] merge to test
- [x] deploy to beta
- [x] document in wiki
- [ ] refine detection

Requested by @mcarans ; CC @danmihaila

**Comment by davidmegginson** [comment]
Sample dataset from Mike: https://data.humdata.org/dataset/afghanistan-natural-disaster-incidents-in-2018

**Comment by mcarans** [comment]
For information: https://data-gov.tw.rpi.edu/wiki/CSV_files_use_delimiters_other_than_commas

**Comment by davidmegginson** [comment]
The built-in csv.Sniffer class chokes on Unicode characters beyond the ASCII range, so it's a no-go. I'll have to write the detection by hand.

**Comment by davidmegginson** [comment]
Sample TSV link from @mcarans is working in beta:

https://beta.proxy.hxlstandard.org/data?url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2F001d5cac-9f29-4ad0-af6b-9b359ac12bd9%2Fresource%2Fd8072936-ab2b-49df-9452-4f883e089244%2Fdownload%2Fafghanistan-natural-disaster-incidents-from-january-to-may-2018.csv

**Comment by davidmegginson** [comment]
Working for now, but will leave this issue open to refine the detection algorithm a bit.

**Comment by davidmegginson** [comment]
Closing for this milestone. Will continue in #184
