### ISSUE TITLE
Date not being identified as date in validation

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#167]
Column with #date contains dates but they are not being identified as dates in validation
Here is an example:
https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1vFfic8ctRCyccew0xxKq98vB4m_Z09IHAfEnJ60lHxQ%2Fedit%23gid%3D739391331

**Comment by davidmegginson** [comment]
I created a duplicate issue #169 at about the same time. I'll close this one and work with the other.

**Comment by davidmegginson** [comment]
Confirmed fixed in #169 : https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1vFfic8ctRCyccew0xxKq98vB4m_Z09IHAfEnJ60lHxQ%2Fedit%23gid%3D739391331 (dates no longer show up as invalid)
