### ISSUE TITLE
Inferring issue with datatype consistency check

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#168]
In this, 4 rows have same value, but data type consistency flags them all as errors:
https://data.humdata.org/dataset/1d1d5448-7cf4-4c93-b899-ecf6cd5b1429/resource/fb562af6-9c94-4625-9a0d-c45f70145169/download/dtm-burundi-site-assessment-round-26.xlsx

**Comment by davidmegginson** [comment]
Stalled for now, until I can reproduce outside of Data Check. @mcarans - can you confirm the exact schema that Data Check would be using in this case?

**Comment by mcarans** [comment]
I chose "No Country" in data check so it should be using the basic one: https://raw.githubusercontent.com/OCHA-DAP/tools-datacheck-validation/prod/basic-validation-schema.json

**Comment by davidmegginson** [comment]
Thanks @mcarans - still no errors or warnings when I validate via the beta Proxy:

```
$ time curl -F 'schema_url=https://raw.githubusercontent.com/OCHA-DAP/tools-datacheck-validation/prod/basic-validation-schema.json' -F 'url=https://data.humdata.org/dataset/1d1d5448-7cf4-4c93-b899-ecf6cd5b1429/resource/fb562af6-9c94-4625-9a0d-c45f70145169/download/dtm-burundi-site-assessment-round-26.xlsx' https://beta.proxy.hxlstandard.org/actions/validate
{
    "validator": "libhxl-python",
    "timestamp": "2018-05-30T18:07:55.510759",
    "is_valid": true,
    "stats": {
        "info": 0,
        "warning": 0,
        "error": 0,
        "total": 0
    },
    "issues": [],
    "data_url": "https://data.humdata.org/dataset/1d1d5448-7cf4-4c93-b899-ecf6cd5b1429/resource/fb562af6-9c94-4625-9a0d-c45f70145169/download/dtm-burundi-site-assessment-round-26.xlsx",
    "schema_url": "https://raw.githubusercontent.com/OCHA-DAP/tools-datacheck-validation/prod/basic-validation-schema.json"
}
real	0m1.948s
user	0m0.040s
sys	0m0.012s
```

**Comment by davidmegginson** [comment]
I'm stuck with this at this point. Created a Jira issue for Data Check, and will revisit once I have more information. Pushing back to 4.9 (June release) for now. 

https://humanitarian.atlassian.net/browse/HDX-5943

**Comment by mcarans** [comment]
Another one where data type consistency check reports all errors: https://data.humdata.org/dataset/140a45e9-6563-47e7-89b1-9109d89a2211/resource/560600db-6155-4ddf-a8ed-bbd4b753509b/download/dtm-cameroon-baseline-assessment-round-12.xlsx (also reported in HDX-5943)

**Comment by davidmegginson** [comment]
Dan found the clue to resolve this (it was nasty).

I was testing without the parameter _include\_dataset_ (which I'd forgotten about). When Dan tested without, all was fine; when he tested with it, we got the errors.

It turns out that a misplaced "if" statement in the hxl.validation module was skipping the pre-scan of datatypes and values IFF the dataset was already cached (which it was with include\_dataset, so that we could run through again to add a copy to the JSON after validation).

**Comment by davidmegginson** [comment]
Thanks @mcarans and @danmihaila for your patience and persistence with this. Deployed to beta. [dtm-burundi-site-assessment-round-26.xlsx](https://data.humdata.org/dataset/1d1d5448-7cf4-4c93-b899-ecf6cd5b1429/resource/fb562af6-9c94-4625-9a0d-c45f70145169/download/dtm-burundi-site-assessment-round-26.xlsx) and [dtm-cameroon-baseline-assessment-round-12.xlsx](https://data.humdata.org/dataset/140a45e9-6563-47e7-89b1-9109d89a2211/resource/560600db-6155-4ddf-a8ed-bbd4b753509b/download/dtm-cameroon-baseline-assessment-round-12.xlsx) now both validate without the spurious inconsistent-type errors (though the latter still, correctly, reports the type error for #population values).
