### ISSUE TITLE
Double counting of errors p-code adm name combination consistency errors

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#171]
When I put the below into data check, I get 2 of every cell eg. F3,F3,F4,F4,F5,F5...
https://data.humdata.org/dataset/77c97850-4004-4285-94db-0b390a962d6e/resource/d6c0dbac-683d-42d7-82b4-a6379bd4f48e/download/mrt_population_statistics_ons_rgph_2013_2017.xlsx

**Comment by davidmegginson** [comment]
Rule triggering the error:

```
{
    "#meta+comment": "Check p-codes and admin unit names are consistent compared to official COD",
    "#valid_tag": "#adm1+code",
    "#valid_severity": "error",
    "#valid_correlation": "adm1+name",
    "#valid_value+url": "http://beta.proxy.hxlstandard.org/pcodes/mrt-adm1.csv",
    "#description": "A. Inconsistency between P-code and administrative unit name compared to official COD source",
    "#rule_type": "A. Check against official COD sources for valid p-codes and admin unit names",
    "#rule_type_description": "Checks against the official COD for valid p-codes, administrative unit names, and consistency between the two."
  }
```

**Comment by davidmegginson** [comment]
Updated: the problem seems to be that when there are two matching columns, the first one gets reported twice. To review in the next milestone/sprint.

**Comment by davidmegginson** [comment]
Update: may actually concern EnumerationTest, because the error mentions CODs: "A. Inconsistency between P-code and administrative unit name compared to official COD source"

**Comment by davidmegginson** [comment]
This rule causes each cell to be reported twice:
```
{
    "#meta+comment": "Check p-codes and admin unit names are consistent compared to official COD",
    "#valid_tag": "#adm1+code",
    "#valid_severity": "error",
    "#valid_correlation": "adm1+name",
    "#valid_value+url": "http://beta.proxy.hxlstandard.org/pcodes/mrt-adm1.csv",
    "#description": "A. Inconsistency between P-code and administrative unit name compared to official COD source",
    "#rule_type": "A. Check against official COD sources for valid p-codes and admin unit names",
    "#rule_type_description": "Checks against the official COD for valid p-codes, administrative unit names, and consistency between the two."
  },
```
It gets reported once for #valid_correlation, and once for #valid_value+url

**Comment by davidmegginson** [comment]
I can't fix this in the main application logic right now, but I was able to fix specifically for the JSON report that goes to Data Check via the /data/validate endpoint. That means that there will be a discrepancy between /actions/validate and /data/validate until I address HXLStandard/hxl-proxy#224

**Comment by mcarans** [comment]
Please confirm that this is a fix at your end rather than needing a change to the rule in the schema

**Comment by davidmegginson** [comment]
It's a kludge at my end, in any case—I do a final pass to remove any duplicate locations for each rule. We can come up with something more robust later.
