### ISSUE TITLE
Open files from Google Drive

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#175]
The HXL Proxy's URL munging currently works only for Google Sheets, not for actual binary files hosted on Google Drive (e.g. CSV, XLSX).

Originally reported by @macarans in https://humanitarian.atlassian.net/browse/HDX-5944

> Links of the form below (created when sharing xls from Google Drive) do not work in QuickCharts or data check:
> 
> https://drive.google.com/open?id=1Dc3nkxPKjBTFtYTDR490ZjXZtP46yF9g
> 
> https://drive.google.com/file/d/1Dc3nkxPKjBTFtYTDR490ZjXZtP46yF9g/view?usp=sharing
> 
> They need to be converted into this form: https://drive.google.com/uc?authuser=0&id=1Dc3nkxPKjBTFtYTDR490ZjXZtP46yF9g&export=download

**Comment by mcarans** [comment]
From chat with Dan:
The use case is this. Elliot created a dataset on Google Drive and then shared the link to it to me - I can imagine that it might be a use case other humanitarians could use

Although there is a download button, you cannot get the url behind it in Chrome eg. see: https://drive.google.com/file/d/1Dc3nkxPKjBTFtYTDR490ZjXZtP46yF9g/view?usp=sharing

This means the downloadable link is not easily shareable.

**Comment by davidmegginson** [comment]
Agreed. If this becomes a high priority (e.g. because a key HDX user needs it), we can hotfix earlier; otherwise, it will be in the 4.9 release on 29 June.

**Comment by davidmegginson** [comment]
The "open" link will be problematic, because it can redirect to anything (not just a file download). In release 4.8, libhxl is assuming that it will always redirect to a Google Sheet, but we're going to actually have to get the redirect URL from Google.

**Comment by davidmegginson** [comment]
Hotfix/interim release requested.

**Comment by davidmegginson** [comment]
Check for redirects with Google Drive "open" URLs. Munge Google Drive "file" URLs to get a direct download link.

**Comment by davidmegginson** [comment]
Original problem link now opening in beta Proxy: https://beta.proxy.hxlstandard.org/data?url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D1Dc3nkxPKjBTFtYTDR490ZjXZtP46yF9g
