### ISSUE TITLE
Allow configurable user-agent string

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#193]
Suggested by @alexandru-m-g 

A configurable UA string will make it easier to track HXL Proxy downloads in analytics.

**Comment by alexandru-m-g** [comment]
1.  Making the UA configurable would not only help with tracking which requests are coming from the HXL Proxy but also with knowing from which particular HXL Proxy instance is it coming from.
1.  It would also be helpful to know if a download request coming from the HXL Proxy is meant just for checking whether that resource is hxlated or for processing (and ultimately returning) data for a user. Not sure on what's the best way of achieving this but some options would be:
    *  adding a parameter to the GET request (ex: &purpose=hxlcheck). CKAN wouldn't have a problem with this but I imagine that some systems might
    *  adding a specific cookie to the HEADER (ex: Cookie: purpose=hxlcheck;)
    *  adding some non-standard HTTP request header

**Comment by davidmegginson** [comment]
Added an optional _http\_headers_ param to hxl.io.data (and related functions).

The param is an optional dictionary of headers like

```
{
    'User-Agent': 'libhxl-python'
}
```

Added a unit test to ensure that the param is accepted, but not testing that requests library actually passes it on (yet).
