### ISSUE TITLE
Aggregate multiple values into a single cell

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#197]
In the aggregation filter, add support for aggregating a delimited list of unique values for a column.  For example, given

```
#org, #sector 
Org A, Health
Org B, Health
Org A, WASH
```

aggregate to

```
#org, #sector+list, #meta+count
Org A, Health|WASH, 2
Org B, Health, 1
```

**Comment by SimonbJohnson** [comment]
A use case came up for this today and might be good to test with.  Rumour analysis from the DRC Ebola response.  It's long data with the rumour being repeated and no Unique ID.  I wanted to quickly roll up based on a few columns for approximate uniqueness.

https://docs.google.com/spreadsheets/d/12z67qIUnTdVd3hgVwJB0HfDnNTFWjdEJkqaJq4M8AQg/edit#gid=1788434173

Having this filter with the keywords, would be brilliant
https://proxy.hxlstandard.org/data/edit?filter01=count&count-tags01=%23date%2Bweek%2C%23indicator%2Bcategory%2C%23adm2&count-type01-01=count&count-header01-01=Count&count-column01-01=%23meta%2Bcount&tagger-match-all=on&tagger-01-header=date&tagger-01-tag=%23date&tagger-02-header=zone+de+sante&tagger-02-tag=%23adm1%2Bhealth&tagger-03-header=aire+de+sante&tagger-03-tag=%23adm2%2Bhealth&tagger-04-header=type&tagger-04-tag=%23indicator%2Btype&tagger-05-header=histoire&tagger-05-tag=%23indicator%2Bcategory&tagger-06-header=nombre+de+fois&tagger-06-tag=%23value%2Boccurence&tagger-07-header=mot+cle&tagger-07-tag=%23indicator&tagger-08-header=category&tagger-08-tag=%23indicator&tagger-09-header=week&tagger-09-tag=%23date%2Bweek&header-row=1&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F12z67qIUnTdVd3hgVwJB0HfDnNTFWjdEJkqaJq4M8AQg%2Fedit%23gid%3D1788434173

**Comment by davidmegginson** [comment]
Implemented first pass (delimiter hard-coded to "|" for now).

**Comment by davidmegginson** [comment]
Deployed to beta.
