### ISSUE TITLE
Add a datedif function for row formulas

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#202]
Requested by @SimonbJohnson 

Base it on this: https://support.office.com/en-us/article/DATEDIF-function-25dba1a4-2812-480b-84dd-8b32a451b35c

**Comment by SimonbJohnson** [comment]
Is it also possible to have Weeks as a unit parameter?

**Comment by davidmegginson** [comment]
Certainly -- will add.

Would you want it to up and down, or just up to the nearest week? e.g. would a 9-day difference be 1 week or two?

**Comment by SimonbJohnson** [comment]
Complete weeks would be great.

**Comment by davidmegginson** [comment]
Added datedif() function, and documented here: https://github.com/HXLStandard/hxl-proxy/wiki/Row-formulas

Supports years, months, weeks, and days as units of difference.

Deployed to beta. Demo link: https://beta.proxy.hxlstandard.org/data/edit?filter01=add&add-tag01=%23x_diff%2Bweeks&add-value01={{datedif(%23date%2Bstart%2C%23date%2Bend%2C+%22W%22)}}&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1SaOnxGLu2jahCrGtaQDcYe1H-nlm_zCDags-DoW9uTI%2Fedit%23gid%3D0
