### ISSUE TITLE
Improve error reporting when external taxonomy not available

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#211]
Revisiting #137 

When an external taxonomy is not available, the error reporting is not clear. See https://humanitarian.atlassian.net/browse/HDX-6364

- [x] fix 404 return value from Proxy
- [x] catch 404 exception properly in libhxl
- [x] separate external_issues
- [x] use the system error message instead of the rule description with external issues for clarify
- [x] don't list empty locations for external issues
- [x] deploy to beta Proxy
- [x] sign-off from dev team

attn @alexandru-m-g @danmihaila @cjhendrix

**Comment by davidmegginson** [comment]
@alexandru-m-g wants an unambiguous way to distinguish these from other errors, so that Data Check can report them differently.

**Comment by davidmegginson** [comment]
Example of current error:
```
{
    "validator": "libhxl-python",
    "timestamp": "2019-02-27T12:01:29.615378",
    "is_valid": False,
    "stats": {
        "info": 0,
        "warning": 0,
        "error": 1,
        "total": 1
    },
    "issues": [
        {
            "rule_id": "mmFhtnVI",
            "tag_pattern": "#adm1+code",
            "description": "Error loading allowed values from http://example.org/xxx-missing-taxonomy.csv: [Errno 2] No such file or directory: \"/home/david/Source/HXL/libhxl-python/tests/files/mock/xxx-missing-taxonomy.csv\"",
            "severity": "error",
            "location_count": 1,
            "scope": "dataset",
            "locations": [{}]
        }
    ]
}
```

**Comment by davidmegginson** [comment]
An external issue doesn't make the dataset invalid, but gets reported in a separate list, _external\_issues_ : 
```
{
  "validator": "libhxl-python",
  "timestamp": "2019-02-27T15:11:24.971105",
  "is_valid": true,
  "stats": {
    "info": 0,
    "warning": 0,
    "error": 0,
    "external": 1,
    "total": 1
  },
  "issues": [],
  "external_issues": [
    {
      "rule_id": "mmFhtnVI",
      "tag_pattern": "#adm1+code",
      "description": "Error loading allowed values from http://example.org/xxx-missing-taxonomy.csv: [Errno 2] No such file or directory: '/home/david/Source/HXL/libhxl-python/tests/files/mock/xxx-missing-taxonomy.csv'",
      "severity": "error",
      "location_count": 1,
      "scope": "dataset",
      "locations": [
        null
      ]
    }
  ]
}
```

**Comment by davidmegginson** [comment]
Updated wiki: https://github.com/HXLStandard/hxl-proxy/wiki/Validation-reports

**Comment by davidmegginson** [comment]
@alexandru-m-g or @danmihaila - can you please test with beta.proxy.hxlstandard.org and confirm that the revised error format works for you?

**Comment by davidmegginson** [comment]
@alexandru-m-g found an issue where non-external errors were being included in the external-error list due to a shared hash table (if the first error was external, then other errors from the same rule were also included in the external list).

**Comment by davidmegginson** [comment]
@danmihaila reports OK to close.

**Comment by danmihaila** [comment]
https://beta.proxy.hxlstandard.org/pcodes/civ-adm4.csv

**Comment by davidmegginson** [comment]
NoneType error has returned.

**Comment by davidmegginson** [comment]
This is now returning the correct 404 error again: https://beta.proxy.hxlstandard.org/pcodes/civ-adm4.csv

**Comment by davidmegginson** [comment]
@danmihaila @alexandru-m-g - can you test the beta Proxy again? It should be behaving better now. I've attached a copy of the output from your test file and schema.

[validation-output.txt](https://github.com/HXLStandard/libhxl-python/files/3010522/validation-output.txt)

**Comment by davidmegginson** [comment]
Closing here, but will keep Jira issue open until after release, so that they can test it in their infrastructure.
