### ISSUE TITLE
Merge columns does not need to have the same hxl tag for shared key

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#221]
We have two datasets where people have tagged columns differently (meta+id and crisis+code).  It would be great to still be able to merge on these columns.

See HXLStandard/libhxl-python#104 for bulk of the implementation

- [ ] add support to libhxl
- [ ] add UI support in Proxy
- [ ] add backend support in Proxy
- [ ] deploy to beta for testing
- [ ] document in wiki

**Comment by davidmegginson** [comment]
Duplicate of #104
