### ISSUE TITLE
space after plus leads to the core tag not being brought through on append

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#222]
Originally was "#geo + lon" and "#adm2 + name"

<img width="941" alt="Screen Shot 2019-03-18 at 16 52 13" src="https://user-images.githubusercontent.com/2110742/54547721-37b85b00-499e-11e9-86c3-726ff44e622d.png">

**Comment by davidmegginson** [comment]
Improved logging for hashtag-parsing errors. Will now need UI support in the Proxy.
