### ISSUE TITLE
Explode filter doesn't work if extra attributes present

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#223]
I expected this to work on the #capacity columns, but the proxy treated them all individually due to them having extra attributes.

Could explode work on just a tag instead?  I am thinking of ebola and also needing to use #affected+confirmed, #affected+probable, #affected+suspected, #affected+deaths as long sometimes and it is unlikely to ever have +label on it.

https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1qEB53VLEDQ8i2Huy5_090t8NksRmn0XvbpiT93ARhCo%2Fedit%23gid%3D0

**Comment by davidmegginson** [comment]
The explode filter is a bit paranoid right now, and treats columns as equivalent only when they have exactly the same attributes. I will look into adding a "fuzzy" option or something similar.
