### ISSUE TITLE
Long to wide

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#225]
Sometime I need to change from long format to wide for dashboard use.

In this example I would like the #activity variable to be wide

https://proxy.hxlstandard.org/data/edit?filter01=count&count-tags01=%23date%2C%23activity&count-type01-01=count&count-header01-01=Count&count-column01-01=%23meta%2Bcount&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F17rfYPMVNYh3R1U8O8eT-6czurpJCs3H7vDDEM2tHf_8%2Fedit%23gid%3D0

**Comment by davidmegginson** [comment]
Duplicates #64

**Comment by davidmegginson** [comment]
Finished here. See https://github.com/HXLStandard/hxl-proxy/issues/304 for UI support in the HXL Proxy.
