### ISSUE TITLE
Valid xlsx not read

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#232]
`hxl.data('https://api.idmcdb.org/api/disaster_data/xlsx?ci=IDMCWSHSOLO009&filename=idmc_disaster_all_dataset.xlsx')` fails even though the url points to a valid xlsx.

I'm using libhxl 4.15.1.

The error raised is `hxl.io.HXLIOException: <HXLException: Not an Excel workbook (possibly a zip archive)>`

I think it is this call that is throwing the exception:
            `self._workbook = xlrd.open_workbook(file_contents=input.read())`

Downloading the file and loading using `hxl.data(path, allow_local=true)` works so I have a workaround.

**Comment by davidmegginson** [comment]
It works opening it directly with the Python xlrd library, so the problem must be in the buffering in hxl.io. Investigating.

**Comment by davidmegginson** [comment]
The problem is the zip file support that libhxl added a while back. Because this server is sending out the file with content-type: application/zip, libhxl is trying to extract a CSV file from it rather than passing it on to the Excel library.

**Comment by davidmegginson** [comment]
Fix deployed to beta Proxy. 

Confirmation link: https://beta.proxy.hxlstandard.org/data?url=https%3A%2F%2Fapi.idmcdb.org%2Fapi%2Fdisaster_data%2Fxlsx%3Fci%3DIDMCWSHSOLO009%26filename%3Didmc_disaster_all_dataset.xlsx

**Comment by davidmegginson** [comment]
Failing on zipped CSV. Reopening.

**Comment by davidmegginson** [comment]
Confirmation link is working now.
