### ISSUE TITLE
hxl/filters.py:463: SyntaxWarning: "is" with a literal. Did you mean "=="

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#237]
I see the warning:
hxl/filters.py:463: SyntaxWarning: "is" with a literal. Did you mean "=="

```
        # Skip empty values
        if value is '' or value is None:
            return
```
Just checking it's not a bug.

**Comment by davidmegginson** [comment]
Good catch. I will replace that with hxl.datatypes.is_empty() — I'm trying to centralise all the datatype/data-conversion logic.
