### ISSUE TITLE
Rename hxl.parser to hxl.io

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#27]
The hxl.parser name doesn't adequately describe the module any longer. Change it to hxl.io (this will require a change to HXL Proxy as well).

**Comment by timgdavies** [comment]
The documentation at https://github.com/HXLStandard/libhxl-python/wiki/hxl.parser-%28module%29 needs updating to reflect this change. 

Happy to make the changes if useful - but I wasn't sure if this was being auto-generated in some way...

**Comment by davidmegginson** [comment]
Thanks, Tim. I'll gladly take up your offer of help — I've added you as a developer so that you can edit the wiki.

**Comment by timgdavies** [comment]
ok. I've done an initial rename of parser to io, but realising that there are greater changes than that. 

I'll come back to this and try and improve docs further as I explore the tools and get my head around all the functionality now in .io

**Comment by davidmegginson** [comment]
I owe the wiki a lot of TLC —it's months out of date.
