### ISSUE TITLE
Improve error reporting for malformed hashtags and attributes

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#270]
Based on #269, originally reported by @mcarans

If more than 75% of the hashtag specs in a row are malformed, libhxl will simply assume that it's not meant to be the hashtag row, but that error isn't helpful if the hashtag specs were accidentally malformed, like in this example:

#affected+idps+ind+year+2013+2014

Instead, see if there's a row that _might_ be meant as the hashtag row, and if so, provide more-meaningful messages about syntax errors.

**Comment by mcarans** [comment]
I'm not sure if I should put this here or in a new ticket: perhaps in addition to for each row calculating a percentage until a fuzzy threshold is exceeded, also store those percentages and if you hit the max number of rows (25 I think it is) without the threshold being reached, use the row with the highest percentage of the 25 provided it exceeds a lower threshold. Just an idea to handle malformed hashtags (but the error reporting is still needed).
