### ISSUE TITLE
Source files encoding granted to work without additional parameters and how to force source files with non-UTF 8 encoding

### ISSUE THREAD

**Issue by fititnt** [HXLStandard/libhxl-python#272]
- **This question affects .csv files**.
  - JSON, as per specification (https://tools.ietf.org/html/rfc8259), _" JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [RFC3629]."_
  - I assume when HXL is used on XLS, XLSX, the encoding is also enforced. (At least for now, Did not had any issues

---

### [Question] The encoding granted to work out of the box

I have the following assumptions about both libhxl-python when used in other applications and via hxl-proxy:

1. ASCII files
2. Non ASCII files "but not using only ASCII (standard English letters and arabic numbers)"
3. Well encoded UTF-8 (without BOM)
4. Well encoded UTF-8 (with BOM)

**So the question is: in theory, is this correct?** (I think that this is more a question related to the python csv than the libhxl itself.)

### [Feature] Way to specific source encoding on `hxltag`

All [HXL Command line tools](https://github.com/HXLStandard/libhxl-python/wiki/Command-line-tools) already assume that all HXL input already are UTF8. But some cases, at least on the first command, this may not be true. So my question: **is possible to add an additional parameter to the HXL Command line tools to specify the source encoding explicitly**? (note: this is about only the source encoding, not the output encoding)

In special the `hxltag` (Quick description: _"Add HXL tags to a raw CSV file."_) does not have some way for explicitly cite the source encoding and will raise exception (like _"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 1893: invalid continuation byte"_), but the libxhl-python already seems to have on most part of the code places to specify the source encoding (so this extra parameter is just not exposed).

#### Auto discover features of encoding 
In theory, I think is possible to try guess the encoding and, at least for the `hxltag`, may eventually worth the effort to (at least if this does not affect the use on HXL-proxy) implement this. But this issue is just asking about be able to explicitly define on `hxltag`. But since when scanning the file the hxllib already is doing `sample = input.peek(16384).decode(encoding)`, maybe in addition to the exact part of the error (e.g. still show message like 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 1893: invalid continuation byte', or at least the 1893 number), also one friendly message that the source file may have bad encoding. This alone could help the user to explicitly define the source encoding.

**Comment by davidmegginson** [comment]
Thanks for the report.

To do: add an --encoding option to the HXL command-line tools.
