### ISSUE TITLE
Make _munge_url public

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#291]
I am using `_munge_url` in HDX Python API. Ideally I'd like it to be made public.

**Comment by davidmegginson** [comment]
I won't make the change now, because we're close to end of quarter release, but I'll add this for next quarter. It will involve renaming the function, but we can still support the old name as well (deprecated).

**Comment by davidmegginson** [comment]
In the prerelease for 4.26, the function is now munge_url() (without the leading underscore).
