### ISSUE TITLE
Improve detection of which sheet has HXL hashtags in xlsx

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#292]
[iom_dtm_sdn_dtm_sudan_idps_master_list_round_3.xlsx](https://github.com/HXLStandard/libhxl-python/files/8828121/iom_dtm_sdn_dtm_sudan_idps_master_list_round_3.xlsx) illustrates the problem.

In the first sheet, the contributors have unfortunately used what look like HXL tags:
#States	#Localities	#Locations	#IDP Households	#Individuals

However, it is clear that the second sheet is the real HXLated sheet. It has:
#date+assessment	#adm1+name	#adm1+code	#adm2+name	#adm2+code	#adm3+name	#adm3+code	#geo+lat	#geo+lon	#loc+type	#loc+class	#affected+idps+hh	#affected+idps+ind

Would it be possible for the library to work out a score for each sheet? The score would increase based on things like this:

- number of HXL hashtags in the HXL standard (like #adm1+code etc.)
- if all the hashtags are on one row
- if the hashtags have attributes

For speed reasons, there could be a threshold score that can be reached. Iterating through the sheets, the first to reach that threshold would be chosen and no further computation of scores performed. Obviously, that threshold would need to be higher than the score of the first sheet in the example xlsx otherwise the wrong sheet will be chosen.  If no sheets meet that threshold then compare the sheets' scores after scoring them all.

**Comment by davidmegginson** [comment]
The best approach would be to specify the sheet, but I understand why that wouldn't work with something like automated Quick Charts.

**Comment by mcarans** [comment]
> The best approach would be to specify the sheet, but I understand why that wouldn't work with something like automated Quick Charts.

In this case, it is part of an automated process that does not know in advance the correct sheet to use.
