### ISSUE TITLE
Do not log attempts to access local machine as CRITICAL

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#303]
Requested by @teodorescuserban — see https://github.com/HXLStandard/hxl-proxy/issues/400

**Comment by davidmegginson** [comment]
@teodorescuserban - the test branch of libhxl-python no longer logs a CRITICAL error for attempts to access the local filesystem. Please test with hxl-proxy if/when you have a chance.

**Comment by teodorescuserban** [comment]
> @teodorescuserban - the test branch of libhxl-python no longer logs a CRITICAL error for attempts to access the local filesystem. Please test with hxl-proxy if/when you have a chance.

@davidmegginson , yes, after pulling the latest `test` libhxl-python on beta, it does work.

```
[2022-08-04 13:07:09,610] ERROR in hxl.input: Security settings forbid accessing local files or non http(s)/ftp(s) URL schemes: passwd
```

**Comment by davidmegginson** [comment]
Thank you, @teodorescuserban ! Closing.
