### ISSUE TITLE
munge_url returns broken url

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#336]
The munge_url returns a broken url in this example which uses a resource from the [IATI Bahrain dataset](https://data.humdata.org/dataset/iati-bhr):

```python
from hxl.input import InputOptions, munge_url
url = "https://proxy.hxlstandard.org/data/download/iati-bhr.csv?filter01=cut&cut-skip-untagged01=on&filter02=add&add-tag02=%23country%2Bcode%2Bv_iso3&add-value02=BHR&add-header02=iso3&filter03=add&filter-label03=Add+ISO2+code&add-tag03=%23country%2Bcode%2Bv_iso2&add-value03=BH&add-header03=iso2&filter04=add&filter-label04=Copy+the+URL+to+a+new+column+at+the+end&add-tag04=%23activity%2Burl&add-value04=%7B%7B%23activity%2Bid%7D%7D&add-header04=activity_id&filter05=replace&filter-label05=Extract+the+IATI+activity+ID+from+the+URL&replace-pattern05=%5E.*aid%3D%28.%2B%29%24&replace-regex05=on&replace-value05=%5C1&replace-tags05=%23activity%2Bid&tagger-match-all=on&tagger-01-header=aid&tagger-01-tag=%23activity%2Bid&tagger-02-header=reporting&tagger-02-tag=%23org%2Breporting%2Bname&tagger-03-header=reporting_ref&tagger-03-tag=%23org%2Breporting%2Bid&tagger-04-header=funder_ref&tagger-04-tag=%23org%2Bfunder%2Bid&tagger-05-header=title&tagger-05-tag=%23activity%2Btitle&tagger-07-header=status_code&tagger-07-tag=%23status&tagger-08-header=day_start&tagger-08-tag=%23date%2Bstart&tagger-09-header=day_end&tagger-09-tag=%23date%2Bend&tagger-11-header=description&tagger-11-tag=%23description&tagger-12-header=commitment&tagger-12-tag=%23value%2Bcommitted%2Busd&tagger-13-header=spend&tagger-13-tag=%23value%2Bspent%2Busd&tagger-14-header=commitment_eur&tagger-14-tag=%23value%2Bcommitted%2Beur&tagger-15-header=spend_eur&tagger-15-tag=%23value%2Bspent%2Beur&tagger-16-header=commitment_gbp&tagger-16-tag=%23value%2Bcommitted%2Bgbp&tagger-17-header=spend_gbp&tagger-17-tag=%23value%2Bspent%2Bgbp&tagger-18-header=commitment_cad&tagger-18-tag=%23value%2Bcommitted%2Bcad&tagger-19-header=spend_cad&tagger-19-tag=%23value%2Bspent%2Bcad&tagger-21-header=country_code&tagger-21-tag=%23country%2Bname&tagger-22-header=country_percent&tagger-22-tag=%23indicator%2Bcountry_allocation%2Bpct&tagger-23-header=sector_group&tagger-23-tag=%23sector&tagger-24-header=sector_code&tagger-24-tag=%23subsector&tagger-25-header=sector_percent&tagger-25-tag=%23indicator%2Bsubsector_allocation%2Bpct&tagger-26-header=location_code&tagger-26-tag=%23loc%2Bcode&tagger-29-header=location_name&tagger-29-tag=%23loc%2Bname&tagger-30-header=location_longitude&tagger-30-tag=%23geo%2Blon&tagger-31-header=location_latitude&tagger-31-tag=%23geo%2Blat&tagger-32-header=location_precision&tagger-32-tag=%23geo%2Bprecision%2Bcode&tagger-33-header=location_percent&tagger-33-tag=%23indicator%2Blocation_allocation%2Bpct&header-row=1&url=http%3A%2F%2Fd-portal.org%2Fdquery%3Fform%3Dcsv%26human%3D1%26sql%3Dselect+*+from+act+left+join+country+using+%28aid%29+left+join+sector+using+%28aid%29+left+join+location+using+%28aid%29+where+status_code%253D2+and+country.country_code%253D%27BH%27+and+day_end+%3E%253D+floor%28extract%28epoch+from+now%28%29%29%252F%2860*60*24%29%29+order+by+day_start%252C+day_end%252C+reporting%26_gl%3D1*avmz6m*_ga*MTQ0Nzk3MzM5OS4xNjY3MjI2ODk2*_ga_E60ZNX2F68*MTY4MTc0NjM3OC43OS4xLjE2ODE3NDYzODkuNDkuMC4w"
broken_url = munge_url(url, InputOptions())
```

The broken url it gives is: `https://proxy.hxlstandard.org/data/downlo.csv?filter01=cut&cut-skip-untagged01=on&filter02=add&add-tag02=%23country%2Bcode%2Bv_iso3&add-value02=BHR&add-header02=iso3&filter03=add&filter-label03=Add+ISO2+code&add-tag03=%23country%2Bcode%2Bv_iso2&add-value03=BH&add-header03=iso2&filter04=add&filter-label04=Copy+the+URL+to+a+new+column+at+the+end&add-tag04=%23activity%2Burl&add-value04=%7B%7B%23activity%2Bid%7D%7D&add-header04=activity_id&filter05=replace&filter-label05=Extract+the+IATI+activity+ID+from+the+URL&replace-pattern05=%5E.*aid%3D%28.%2B%29%24&replace-regex05=on&replace-value05=%5C1&replace-tags05=%23activity%2Bid&tagger-match-all=on&tagger-01-header=aid&tagger-01-tag=%23activity%2Bid&tagger-02-header=reporting&tagger-02-tag=%23org%2Breporting%2Bname&tagger-03-header=reporting_ref&tagger-03-tag=%23org%2Breporting%2Bid&tagger-04-header=funder_ref&tagger-04-tag=%23org%2Bfunder%2Bid&tagger-05-header=title&tagger-05-tag=%23activity%2Btitle&tagger-07-header=status_code&tagger-07-tag=%23status&tagger-08-header=day_start&tagger-08-tag=%23date%2Bstart&tagger-09-header=day_end&tagger-09-tag=%23date%2Bend&tagger-11-header=description&tagger-11-tag=%23description&tagger-12-header=commitment&tagger-12-tag=%23value%2Bcommitted%2Busd&tagger-13-header=spend&tagger-13-tag=%23value%2Bspent%2Busd&tagger-14-header=commitment_eur&tagger-14-tag=%23value%2Bcommitted%2Beur&tagger-15-header=spend_eur&tagger-15-tag=%23value%2Bspent%2Beur&tagger-16-header=commitment_gbp&tagger-16-tag=%23value%2Bcommitted%2Bgbp&tagger-17-header=spend_gbp&tagger-17-tag=%23value%2Bspent%2Bgbp&tagger-18-header=commitment_cad&tagger-18-tag=%23value%2Bcommitted%2Bcad&tagger-19-header=spend_cad&tagger-19-tag=%23value%2Bspent%2Bcad&tagger-21-header=country_code&tagger-21-tag=%23country%2Bname&tagger-22-header=country_percent&tagger-22-tag=%23indicator%2Bcountry_allocation%2Bpct&tagger-23-header=sector_group&tagger-23-tag=%23sector&tagger-24-header=sector_code&tagger-24-tag=%23subsector&tagger-25-header=sector_percent&tagger-25-tag=%23indicator%2Bsubsector_allocation%2Bpct&tagger-26-header=location_code&tagger-26-tag=%23loc%2Bcode&tagger-29-header=location_name&tagger-29-tag=%23loc%2Bname&tagger-30-header=location_longitude&tagger-30-tag=%23geo%2Blon&tagger-31-header=location_latitude&tagger-31-tag=%23geo%2Blat&tagger-32-header=location_precision&tagger-32-tag=%23geo%2Bprecision%2Bcode&tagger-33-header=location_percent&tagger-33-tag=%23indicator%2Blocation_allocation%2Bpct&header-row=1&url=http%3A%2F%2Fd-portal.org%2Fdquery%3Fform%3Dcsv%26human%3D1%26sql%3Dselect+*+from+act+left+join+country+using+%28aid%29+left+join+sector+using+%28aid%29+left+join+location+using+%28aid%29+where+status_code%253D2+and+country.country_code%253D%27BH%27+and+day_end+%3E%253D+floor%28extract%28epoch+from+now%28%29%29%252F%2860*60*24%29%29+order+by+day_start%252C+day_end%252C+reporting%26_gl%3D1*avmz6m*_ga*MTQ0Nzk3MzM5OS4xNjY3MjI2ODk2*_ga_E60ZNX2F68*MTY4MTc0NjM3OC43OS4xLjE2ODE3NDYzODkuNDkuMC4w`

It looks like it is removing these characters: "ad/iati-bhr" from the original url.

**Comment by davidmegginson** [comment]
Fixed in the dev branch
