### ISSUE TITLE
Support wide data

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#49]
When many columns have the same tag but different attributes, provide a way to convert to wide data (and vice-versa).

**Comment by SimonbJohnson** [comment]
+1

Can see a number of situation where this would be useful at the RC and made a tool to do it already
http://simonbjohnson.github.io/hxl-web-tools/hxl-wide2long.html

**Comment by davidmegginson** [comment]
Implemented in c7e1b7cea7d4ec3632a34874080408f3c295312b with the new ExplodeFilter
