### ISSUE TITLE
Convert long data to wide data

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#64]
Add support for imploding a long dataset into a wide one, by specifying which columns contain labels and which contain values. For example, change

```
Province,Year,Number affected
#adm1,#date+year,#affected
Coast,2010,100
Coast,2011,200
Coast,2012,150
Plains,2010,75
Plains,2011,80
Plains, 2012,10
```

to

```
Province,2010,2011,2012
#adm1,#affected+label,#affected+label,#affected+label
Coast,100,200,150
Plains,75,80,10
```

**Comment by Midnighter** [comment]
I know that HXL has a different base library but have you at some point in the development considered using [pandas](http://pandas.pydata.org/) for the Python functionality? It's a great table/data frame/spreadsheet package and I doubt it's worthwhile re-implementing all of that behaviour. The only issue I see is that pandas normally only expects one header row.

**Comment by davidmegginson** [comment]
Thanks for the suggestion, @Midnighter -- it looks like this is the pandas functionality we'd want:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html

This feature suggestion is pushing at the dividing line between libhxl (a streaming-data library, supporting online data proxies) and pandas (an analytical library), and even if we do go ahead and implement this feature, I'd agree that it's probably as far as we should go in that direction; any further analytical work should happen somewhere like pandas, and we should add some integration to make that handoff easy.

**Comment by Midnighter** [comment]
I think a conversion function for objects is a great idea. I'd be happy to help out there since I'm quite familiar with pandas. If you have concrete ideas  what to implement or want further input from me, just ping me.

**Comment by davidmegginson** [comment]
Newly prioritised for World Bank data.

cc @mcarans @cjhendrix

**Comment by davidmegginson** [comment]
Duplicated by #225
