### ISSUE TITLE
Support comma-separated lists

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#69]
Often, data providers will list multiple items in the same cell. Support this with a +list attribute and the various filters.

**Comment by SimonbJohnson** [comment]
As a dev the option of getting the list properly nested in the json output would be fantastic.  I'm not sure that works with the current paradigm though as it brings in a difference between the csv and json output, so may not be suitable.

**Comment by davidmegginson** [comment]
We can definitely have an option in the library to have the data parsed out; then it would just be a matter of how each output format wanted it represented.

**Comment by davidmegginson** [comment]
Added first support with 3588c71cf5

This is just a barebones version that adds an optional _parsed_ parameter to hxl.Row.get, e.g.

    values = myRow.get('#sector', parsed=True)

In this case, if the #sector column as the +list attribute **and** the _parsed_ parameter is _True_, the result will be a list of values.

Next step: try adding to hxl.filters.CountFilter and hxl.filters.SelectRowsFilter

**Comment by davidmegginson** [comment]
Continued in #74
