### ISSUE TITLE
Clean zombie params

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#71]
Params from old/changed filters can stick around in the URL. They're harmless, but cause bloated URLs.  Clean them out on the edit page.

Reported by @danmihaila

**Comment by danmihaila** [comment]
also, please note the removal of current filters is not working. I remember when switching to "no data" it was replacing the filter.
Maybe a delete icon/button will help

**Comment by davidmegginson** [comment]
Oops -- this issue belongs to the HXL Proxy.
