### ISSUE TITLE
Use external list for append filter

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#79]
Add support for using an external list with the append filter. That would allow people to (e.g.) keep a list of URLs to merge in an external resource like a Google Sheet.

**Comment by LeMeteore** [comment]
Hey @davidmegginson , really hope you're doing fine. Not yet had the time to get a good understanding of all the code base. But if you're okay to mentor me and to give me some assistance, I'll be glad to help you fix those issues. Thanks a lot.

**Comment by davidmegginson** [comment]
Thank you, @LeMeteore — your participation would be very welcome. Is there a particular part of libhxl-python that interests you most?

**Comment by LeMeteore** [comment]
Everything. I've played just a little bit with the libhxl-python examples and I found it really interesting. Helping you fix thoses issues will help me have a better understanding of the library and the HXL. I also want to contribute, and I think it's a good place to start.

**Comment by davidmegginson** [comment]
Certainly! Feel free to pick an issue (this one, or any other), and I'll be happy to help you get started. If you're on Twitter, you can DM your email address to @ david_megginson there, so that we can communicate more directly.

**Comment by davidmegginson** [comment]
Already implemented via another issue.
