### ISSUE TITLE
Improve date cleaning

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#87]
For the clean filter, add more flexibility to date normalisation:

1. Allow the caller to specify year, year-month, year-quarter, etc. as well as year-month-day.
2. -Allow the caller to provide a default between MM/DD/(YY)YY and DD/MM/(YY)YY where it's ambiguous (e.g. "9/10/16").- (save for a future issue)

**Comment by danmihaila** [comment]
the current issue that we faced is:
- #date column with years: 2004, 2005, 2006
- apply a clean data filter for #date column
- hxl proxy is trying to normalize the values to something "YYYY-MM-DD"

**Comment by davidmegginson** [comment]
As a first step, added support for an optional date_format parameter for the clean filter, defaulting to '%Y-%m-%d'. Will also need to add UI support in the HXL Proxy.

Will need to add UI support in the Proxy. https://github.com/HXLStandard/hxl-proxy/issues/165

**Comment by davidmegginson** [comment]
Deployed to test branch.
