### ISSUE TITLE
Support merged cells in spreadsheets

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#89]
In Excel, cells can be merged. libhxl should replicate the single value in a set of merged cells to all cells in the set. This can occur in the header or the data. Example: https://data.humdata.org/dataset/985b35e6-4bab-4332-af04-6b146be55eb5/resource/062b661b-77a2-4ce6-9676-6f0732c5714b/download/WFPVAM_MM35_Big-Table.xlsx

**Comment by mcarans** [comment]
This could require lookahead eg. there could be a column of merged cells with the value in the last cell of the set and this would need to be replicated upwards (not usual but possible).

**Comment by mcarans** [comment]
https://stackoverflow.com/questions/30727017/read-merged-cells-in-excel-with-python

**Comment by davidmegginson** [comment]
* [ ] unit tests
* [ ] helper method
* [ ] filter class
* [ ] saved-recipe support
* [ ] command-line utility

**Comment by davidmegginson** [comment]
Completed and pushed to the test branch.
