### ISSUE TITLE
Support merged cells in Excel

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#90]
libhxl supports copying value from a cell to empty cells below.

It needs to be extended to support the wider variety of merging that is possible In Excel. This can not only happen in the data but also in the header so the code that tries to map HXL tags to headers would need to be able to cope with this. 

eg. 
set of merged cells (which can be determined using xlrd [merged_cells](http://xlrd.readthedocs.io/en/latest/api.html#xlrd.sheet.Sheet.merged_cells) attribute):

| | | | |
| |a| | |
| | | | |
| | | | |

would become:

|a|a|a|a|
|a|a|a|a|
|a|a|a|a|
|a|a|a|a|

Example: https://data.humdata.org/dataset/985b35e6-4bab-4332-af04-6b146be55eb5/resource/062b661b-77a2-4ce6-9676-6f0732c5714b/download/WFPVAM_MM35_Big-Table.xlsx

Links that might help:
https://stackoverflow.com/questions/41759114/how-to-read-merged-cell-with-xlrd-in-python
https://stackoverflow.com/questions/30727017/read-merged-cells-in-excel-with-python

**Comment by davidmegginson** [comment]
Thanks for this. It will need a fair bit of testing, so I'll postpone this for the 4.1 release this week, and put it near the front of the queue for the next dev cycle.

**Comment by mcarans** [comment]
I have split the headers issue into a separate issue with more explanation: https://github.com/HXLStandard/libhxl-python/issues/92

This issue is now just about merging cells in the data.

**Comment by davidmegginson** [comment]
Won't do (for now)
