### ISSUE TITLE
Support multiline headers

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#92]
Example file:
https://data.humdata.org/dataset/985b35e6-4bab-4332-af04-6b146be55eb5/resource/062b661b-77a2-4ce6-9676-6f0732c5714b/download/WFPVAM_MM35_Big-Table.xlsx

In the above file the headers are between rows 8 and 12 eg. for column F, the header consists of text in F9, F10 and F12. 

Not sure the best way to handle this, but perhaps allow the passing in of a parameter representing the start and end row containing the header eg.
```
hxl_names = [
...
    ('Cumulative impact of changes on cost of food basket from previous quarter', '#x_foodprice+change+qtr'),
    ('Cumulative impact of changes on cost of food basket from baseline (%)', '#x_foodprice+change+baseline')
]

hxl.tagger('../WFPVAM_MM35_Big-Table.xlsx', headers=(8,12), hxl_names, match_all=True, sheet_index=1, allow_local=True).with_columns(columns_to_keep)
```

Thus with `headers=(8,12)`, column F's header should be read as "Seasonally adjusted quarterly change (% change)"

More complicated are the headers in columns L and M where L8 to M10 are merged and consist of one header, but there are subheaders underneath in L11-12 and M11-12.

With `headers=(8,12)`, column L's header should be "Cumulative impact of changes on cost of food basket from previous quarter"
With `headers=(8,12)`, column M's header should be "Cumulative impact of changes on cost of food basket from baseline (%)"

**Comment by davidmegginson** [comment]
This is a challenging problem. If we can find most of this logic in an external library, it will be easier to support, but otherwise, it represents a big change to the libhxl API. That's not necessarily a bad thing—if you've discovered a need, others will, too—but I'd like to delay this one a bit if we can.

**Comment by davidmegginson** [comment]
Won't do (for now)
