### ISSUE TITLE
Function to return type given HXL tag

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/libhxl-python#95]
It would be great to be able to supply a HXL tag and get its type (if available) eg. 
get_type('#value+funding') -> 'number'

A lookup like this:
```
        dataset = hxl.data(hashtag_schema)
        self.hashtag_types = dict()
        for row in dataset:
            self.hashtag_types[row.get('#valid_tag')] = row.get('#valid_datatype')
```

Note: I think attributes may imply types too so would be good to build in support for that too.

**Comment by davidmegginson** [comment]
I like this. It implies that we create a new tab in the core schema for hashtag+attribute datatypes.

**Comment by davidmegginson** [comment]
Won't do in libhxl, but this could be a useful side-service from the HXL Proxy using a different library.
