### ISSUE TITLE
Add JSONpath selector for parsing JSON data

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#99]
Add a selector for finding the HXL data in a JSON dataset.

Currently, the library does a depth-first recursive search for something that looks like HXL data, and also optionally allows a top-level property name. Expand the property name to a full JSONpath.

Requested by @mcarans

See

https://github.com/kennknowles/python-jsonpath-rw
https://pypi.python.org/pypi/jsonpath-ng/1.4.2
https://pypi.python.org/pypi/jsonpath/

**Comment by davidmegginson** [comment]
Actually resolved in a separate issue #166

**Comment by davidmegginson** [comment]
Reopening to support https://github.com/HXLStandard/hxl-proxy/issues/314

#166 did _not_ resolve this issue (still just a simple key selector; also, not working right now).

cc @mcarans

**Comment by davidmegginson** [comment]
Resolved via ef6f76fef3

Also added a --selector argument to all command-line scripts.

The selector can now be either a token (property name in a top-level JSON object) or a full JSONpath expression.

**Comment by mcarans** [comment]
Worked well for https://dashboards-dev.sprinklr.com/data/9043/global-covid19-who-gis.json - now all that is needed for that url is to be able to define HXL tags where there are no headers. (jsonpath = rows)

Didn't work for https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/COVID19_hist_cases_adm0_v5_view/FeatureServer/0/query?outFields=*&where=1%3D1&f=json - I tested jsonpath here: https://jsonpath.com/ and came up with jsonpath=features[*].attributes. I tried in the HXL Proxy and got error: "<HXLException: Could not usable JSON data (need array of objects or array of arrays)>", but the evaluation of the jsonpath should have produced an array of objects.

**Comment by davidmegginson** [comment]
I spotted the problem. When there are multiple matches, the code (right now) takes the first one instead of all of them (assuming that maybe you matched multiple lists or similar). I'll try some tweaks.

**Comment by davidmegginson** [comment]
Resolved the issue with multiple results.

Confirmation link: https://beta.proxy.hxlstandard.org/data/tagger?dest=data_view&url=https%3A%2F%2Fservices.arcgis.com%2F5T5nSi527N4F7luB%2Farcgis%2Frest%2Fservices%2FCOVID19_hist_cases_adm0_v5_view%2FFeatureServer%2F0%2Fquery%3FoutFields%3D%2A%26where%3D1%253D1%26f%3Djson&selector=features%5B%2A%5D.attributes
